language: c

compiler:  
    - gcc

before_script:  
    - mkdir build
    - cd build
    - cmake ..
    - make clean

script: make

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "lounick-github"
    token: $SONAR_TOKEN
script:
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - cd ..
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
